version: "2"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:31300:80
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    command: /bin/bash /entry.sh